- ros_topic_name: "/x500/command/motor_speed"
  gz_topic_name:  "/x500/command/motor_speed"
  ros_type_name: "actuator_msgs/msg/Actuators"
  gz_type_name: "gz.msgs.Actuators"
  direction: ROS_TO_GZ

# - ros_topic_name: "/x500/rotor_0_joint/cmd_roll"
#   gz_topic_name:  "/x500/rotor_0_joint/cmd_roll"
#   ros_type_name: "std_msgs/msg/Float64"
#   gz_type_name: "gz.msgs.Double"
#   direction: ROS_TO_GZ
# - ros_topic_name: "/x500/rotor_1_joint/cmd_roll"
#   gz_topic_name:  "/x500/rotor_1_joint/cmd_roll"
#   ros_type_name: "std_msgs/msg/Float64"
#   gz_type_name: "gz.msgs.Double"
#   direction: ROS_TO_GZ
# - ros_topic_name: "/x500/rotor_2_joint/cmd_roll"
#   gz_topic_name:  "/x500/rotor_2_joint/cmd_roll"
#   ros_type_name: "std_msgs/msg/Float64"
#   gz_type_name: "gz.msgs.Double"
#   direction: ROS_TO_GZ
# - ros_topic_name: "/x500/rotor_3_joint/cmd_roll"
#   gz_topic_name:  "/x500/rotor_3_joint/cmd_roll"
#   ros_type_name: "std_msgs/msg/Float64"
#   gz_type_name: "gz.msgs.Double"
#   direction: ROS_TO_GZ

- ros_topic_name: "/x500/joint_states"
  gz_topic_name: "/world/default/model/x500/joint_state"
  ros_type_name: "sensor_msgs/msg/JointState"
  gz_type_name: "gz.msgs.Model"

- ros_topic_name: "/x500/odometry"
  gz_topic_name: "/model/x500/odometry"
  ros_type_name: "nav_msgs/msg/Odometry"	
  gz_type_name: "gz.msgs.Odometry"
